"""adr007-008 hooks schema

Revision ID: 79d855cd5adf
Revises: e5f6a7b8c9d0
Create Date: 2026-04-22 16:34:52.670285

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '79d855cd5adf'
down_revision: str | None = 'e5f6a7b8c9d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_pending_price_resolution',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('receipt_item_id', sa.BigInteger(), nullable=False),
    sa.Column('existing_stock_item_id', sa.BigInteger(), nullable=False),
    sa.Column('new_price_calculation_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['existing_stock_item_id'], ['warehouse_stock_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['new_price_calculation_id'], ['pricing_price_calculation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['warehouse_receipt_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_item_id', name='uq_warehouse_pending_receipt_item')
    )
    op.create_index('ix_warehouse_pending_existing_stock', 'warehouse_pending_price_resolution', ['existing_stock_item_id'], unique=False)
    op.add_column('procurement_purchase', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_purchase', 'delivered_at')
    op.drop_index('ix_warehouse_pending_existing_stock', table_name='warehouse_pending_price_resolution')
    op.drop_table('warehouse_pending_price_resolution')
    # ### end Alembic commands ###
